debug: true

debug: false
mobs:
  chicken:
    awareness: 16
    herd-tightness: 6
    herd-type: tight
    flee-mode: scatter
    flee-speed: 1.25
    panic-speed: 1.5
    flee-range: 13
    panic-range: 10
    night-herd-radius-multiplier: 0.25
    night-herd-speed-multiplier: 0.25
    predators:
    - ZOMBIE
    - SKELETON
    - CREEPER
    - SPIDER
    - PILLAGER
    - VILLAGER
    - PLAYER
    - WOLF
    - FOX
    graze-crops:
    - WHEAT
    graze-frequency: 6000
    soft-cap-per-biome: 40
    soft-cap-per-chunk: 10
    min-herd-size: 2
    density-throttle-threshold: 14   # Min herd size before density throttling (culling) can occur
    density-throttle-chance-per-mob: 0.05 # Chance per mob to be culled when density throttling occurs
    density-throttle-max-chance: 0.1 # Max chance to be culled when density throttling occurs (caps at this chance even if herd size is much higher than threshold)
    reproduce: true
    reproduce-spacing: 3
    reproduce-rate: 0.25
    reproduce-cooldown-ticks: 12000
    max-herds-per-biome: 3
    overcap-interval-ticks: 2000
    overcap-removals-per-interval: 2
  cow:
    awareness: 24
    herd-tightness: 12
    herd-type: loose
    flee-mode: scatter
    flee-speed: 1.1
    panic-speed: 1.5
    flee-range: 18
    panic-range: 12
    night-herd-radius-multiplier: 0.35
    night-herd-speed-multiplier: 0.5
    predators:
    - ZOMBIE
    - SKELETON
    - CREEPER
    - SPIDER
    - PILLAGER
    - VILLAGER
    - PLAYER
    - WOLF
    - FOX
    graze-crops:
    - WHEAT
    graze-frequency: 6000
    soft-cap-per-biome: 40
    soft-cap-per-chunk: 10
    min-herd-size: 2
    density-throttle-threshold: 14   # Min herd size before density throttling (culling) can occur
    density-throttle-chance-per-mob: 0.05 # Chance per mob to be culled when density throttling occurs
    density-throttle-max-chance: 0.1 # Max chance to be culled when density throttling occurs (caps at this chance even if herd size is much higher than threshold)
    reproduce: true
    reproduce-spacing: 3
    reproduce-rate: 0.25
    reproduce-cooldown-ticks: 12000
    max-herds-per-biome: 3
    overcap-interval-ticks: 2000
    overcap-removals-per-interval: 2
